### ISSUE TITLE
Separate permission to access FAQ Manager

### ISSUE THREAD

**Issue by johnd0e** [GerB/faqmanager#1]
I'd like to let moderators to manage FAQ.

Currently 'FAQ Manager' entry belongs to GENERAL / BOARD CONFIGURATION section.
So to access it user must acquire administrative permission (Administrative permissions / Settings / Can alter board settings/check for updates).

That is very wide permission, so it's not secure to grant it to moderator.

**Comment by GerB** [comment]
If you want to, you can move it to the ACP_CAT_MODS tab ("Extensions") and change the permission to ext_ger/faqmanager only. 

Speaking for myself, I see managing the FAQ as an administration task, so I keep it where it is.

**Comment by johnd0e** [comment]
> you can move it to the ACP_CAT_MODS tab ("Extensions")

Ok.
Could you give me a hint how to do that?

**Comment by GerB** [comment]
Go to ACP -> System -> Module management
Look op de FAQ manager module -> edit -> choose the parent you want it to have.

**Comment by johnd0e** [comment]
I am able to add `FAQ Manager` module, and choose parent.
But I'm not able to access it:
```
General Error
Module not accessible

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/includes/functions_module.php
LINE: 565
CALL: trigger_error()

FILE: [ROOT]/adm/index.php
LINE: 81
CALL: p_master->load_active()
```

Perhaps I've missed some necessary step?

**Comment by GerB** [comment]
Not sure. Maybe you should seek support @phpBB.com, it's a common problem AFAIK
